version: '3.5'
services:
  server-php-fpm:
    build: ./docker/php
    image: jefffrade/ratchet-server:php-fpm
    restart: on-failure
    container_name: jefffrade-ratchet-server-php-fpm
    command: php index.php
    ports:
      - "8080:8080"
    volumes:
      - ./:/server
    networks:
      - ratchet

networks:
  ratchet:
    driver: bridge
    name: ratchet-server
